on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: "listing the files"
        run: ls
        
      - uses: actions/checkout@v3

      - name: "listing the files"
        run: ls
  
